### ISSUE TITLE
Problem running csv2rdf on huse

### ISSUE THREAD

**Issue by annalina** [ISWC-Reproducibility-Track/Paper_611#2]
I've got the following problem (notice that the csv2rdf on hsup worked fine):

Parsing file: EXIOBASE_conversion_software/data/MR_HUSE_2011_v3_3_17.csv
Traceback (most recent call last):
  File "/home/annalina/test/bin/csv2rdf-cli", line 11, in <module>
    load_entry_point('EXIOBASE-conversion-software==0.5', 'console_scripts', 'csv2rdf-cli')()
  File "/home/annalina/test/lib/python3.6/site-packages/EXIOBASE_conversion_software-0.5-py3.6.egg/EXIOBASE_conversion_software/bin/csv2rdf_cli.py", line 57, in main
  File "/home/annalina/test/lib/python3.6/site-packages/EXIOBASE_conversion_software-0.5-py3.6.egg/EXIOBASE_conversion_software/__init__.py", line 22, in conversion
  File "/home/annalina/test/lib/python3.6/site-packages/EXIOBASE_conversion_software-0.5-py3.6.egg/EXIOBASE_conversion_software/csv2rdf.py", line 422, in csv2rdf
  File "/home/annalina/test/lib/python3.6/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/annalina/test/lib/python3.6/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/annalina/test/lib/python3.6/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/annalina/test/lib/python3.6/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/annalina/test/lib/python3.6/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File EXIOBASE_conversion_software/data/MR_HUSE_2011_v3_3_17.csv does not exist: 'EXIOBASE_conversion_software/data/MR_HUSE_2011_v3_3_17.csv'
mv: cannot stat ‘EXIOBASE_conversion_software/data/flows_merged.nt’: No such file or directory
gzip: output/exiobase_huse.nt: No such file or directory

any suggestions?

**Comment by kuzeko** [comment]
@IKnowLogic @annalina   can we close this issue?

**Comment by IKnowLogic** [comment]
@kuzeko Yes, I will close it
